ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecommerce_app.urls', namespace='ecommerce')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce_app/urls.py
from django.contrib import admin
from django.urls import path
from .views import home, register_user, login_user, product_register, add_to_cart, go_to_cart, increase_cart_items, decrease_cart_items, remove_from_cart, product_detail_tab, profile_page, password_change_done, update_profile_pic, update_username, pay, payment_return, proceed_to_checkout, logout_view

from django.contrib.auth import views as auth_views
app_name = 'ecommerce_app'
urlpatterns = [
    path('', home, name='home'),
    path('register/', register_user, name='register_user'),
    path('login/', login_user, name='login_user'),
    path('product_register/', product_register, name='product_register'),
    path('add_to_cart/<int:product_pk>/', add_to_cart, name='add_to_cart'),
    path('go_to_cart/', go_to_cart, name='go_to_cart'),
    path('increase_cart_items/<int:cart_pk>/', increase_cart_items, name='increase_cart_items'),
    path('decrease_cart_items/<int:cart_pk>/', decrease_cart_items, name='decrease_cart_items'),
    path('remove_from_cart/<int:cart_pk>/', remove_from_cart, name='remove_from_cart'),
    path('product_detail/<int:product_id>/',product_detail_tab,name='product_detail_tab'),
    path('profile_page/<int:profile_id>',profile_page, name='profile_page'),
    path('update_profile_pic/',update_profile_pic, name='update_profile_pic'),
    path('update_username/',update_username, name='update_username'),

    # path('change_password/', auth_views.PasswordChangeView.as_view(template_name='change_password.html'))
      path('change-password/', auth_views.PasswordChangeView.as_view(
        template_name='change_password.html',
        success_url='/change-password/done/'
    ), name='password_change'),

     path('change-password/done/', password_change_done, name='password_change_done'),

     path('proceed-to-checkout/', proceed_to_checkout, name='proceed_to_checkout'),
     path('return-to-me/', payment_return, name='payment_return'),
     path('pay/', pay, name='pay'),
     path('logoutpage/', logout_view, name='logout')
    #  path('add_to_cart_in')

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Beardo Clone</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
</head>
<body>
    {% include 'navbar.html' %}
    {% block content %}
    
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    
</body>
</html>

templates/navbar.html
{% load static %}
{% if request.user.is_authenticated and request.user.username == "sree"%}
<div class="navbar">
    <div class="logo">
        <a href="#home">EvoFrag</a>
    </div>
    <div>
        <a href="{% url 'ecommerce:home' %}">Home</a>
        <a href="{% url 'ecommerce:product_register' %}">Product</a>
        <a href="#about">About</a>
        <a href="#contact">Contact</a>
    </div>
    <div class="right-icons">
        <a href="{% url 'ecommerce:profile_page' request.user.id %}"><img src="{{ request.user.profile_picture.url }}" alt="User Image" width="30" height="30"></a>
    </div>
{% elif request.user.is_authenticated %}
<div class="navbar">
    <div class="logo">
        <a href="#home">EvoFrag</a>
    </div>
    <div>
        <a href="{% url 'ecommerce:home' %}">Home</a>
        <!-- <a href="#product">Product</a> -->
        <a href="#about">About</a>
        <a href="#contact">Contact</a>
    </div>
    <div class="right-icons">
        <a href="{% url 'ecommerce:go_to_cart' %}" class="right">
            <i class="fa-solid fa-cart-shopping"></i>
            <span class="cart-count">{{ quantity }}</span>
        </a>
        <a href="{% url 'ecommerce:profile_page' request.user.id %}"><img src="{{ request.user.profile_picture.url }}" alt="User Image" width="30" height="30"></a>
    </div>
{% else %}
<div class="navbar">
    <div class="logo">
        <a href="#home">EvoFrag</a>
    </div>
    <div>
        <a href="{% url 'ecommerce:home' %}">Home</a>
        <!-- <a href="#product">Product</a> -->
        <a href="#about">About</a>
        <a href="#contact">Contact</a>
    </div>
    <div class="right-icons">
        <a href="{% url 'ecommerce:login_user' %}" class="right">Login</a>
        <a href="{% url 'ecommerce:register_user' %}" class="right">Register</a>
    </div>
{% endif %}

</div>

templates/trying.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        .card-main-body {
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
            margin: 0;
        }

        .card {
            text-align: center;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        .green-tick {
            color: green;
            font-size: 48px;
            margin-bottom: 10px;
        }
    </style>
    <title>Payment Success</title>
</head>
<body>
<div class="card-main-body">
  <div class="card">
    <div class="green-tick">&#10004;</div>
    <div>
        <p>Your payment is successful.</p>
        <p>Transaction ID: T2403120941246680507857</p>
    </div>
  </div>
</div>


</body>
</html>




{% extends 'base.html' %}
{% block content %}
<div class="card-main-body">
    <div class="card">
      <div class="green-tick">&#10004;</div>
      <div>
          <p>Your payment is successful.</p>
          <p>{{ transact_id }}</p>
          <p> You paid : {{ amount }}</p>
      </div>
    </div>
</div>
<div>
    <a href="{% url 'ecommerce:home' %}">Go to home page</a>
</div>
{% endblock %}




   <!-- Product 1 -->
   {% for product in  %}
   <div class="product-card">
     <img class="product-image" src="{{ product.product_image.url }}" alt="Products">
     <div class="product-info">
         <a href="{% url 'ecommerce:product_detail_tab' product.pk %}"><div class="product-name">{{ product.product_name }}</div></a>
         <div class="product-description">{{ product.product_details }}</div>
         <div class="product-price">${{ product.product_price }}</div>
     </div>
   
     <div class="button-card">
       {% csrf_token %}
           {% if request.user.is_authenticated %}
             {% if product.pk in cart_product_id %}
             <a href="{% url 'ecommerce:go_to_cart' %}"><button style="background-color: #ff6f61">Go to cart</button></a>
             {% else %}
             <a href="{% url 'ecommerce:add_to_cart' product.pk %}"><button>Add to cart</button></a>
             {% endif %}
           {% endif %}

           {% if not request.user.is_authenticated %}
           <a href="{% url 'ecommerce:add_to_cart' product.pk %}"><button>Add to cart</button></a>
           {% endif %}

           <!-- <p>{{ product.pk }}</p> -->
     </div>
   </div>
   {% endfor %}
 