ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecommerce_app.urls', namespace='ecommerce')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce_app/urls.py
from django.contrib import admin
from django.urls import path
from .views import home, register_user, login_user, product_register, add_to_cart, go_to_cart, increase_cart_items, decrease_cart_items, remove_from_cart, product_detail_tab, profile_page, password_change_done, update_profile_pic, update_username, pay, payment_return, proceed_to_checkout, logout_view

from django.contrib.auth import views as auth_views
app_name = 'ecommerce_app'
urlpatterns = [
    path('', home, name='home'),
    path('register/', register_user, name='register_user'),
    path('login/', login_user, name='login_user'),
    path('product_register/', product_register, name='product_register'),
    path('add_to_cart/<int:product_pk>/', add_to_cart, name='add_to_cart'),
    path('go_to_cart/', go_to_cart, name='go_to_cart'),
    path('increase_cart_items/<int:cart_pk>/', increase_cart_items, name='increase_cart_items'),
    path('decrease_cart_items/<int:cart_pk>/', decrease_cart_items, name='decrease_cart_items'),
    path('remove_from_cart/<int:cart_pk>/', remove_from_cart, name='remove_from_cart'),
    path('product_detail/<int:product_id>/',product_detail_tab,name='product_detail_tab'),
    path('profile_page/<int:profile_id>',profile_page, name='profile_page'),
    path('update_profile_pic/',update_profile_pic, name='update_profile_pic'),
    path('update_username/',update_username, name='update_username'),

    # path('change_password/', auth_views.PasswordChangeView.as_view(template_name='change_password.html'))
      path('change-password/', auth_views.PasswordChangeView.as_view(
        template_name='change_password.html',
        success_url='/change-password/done/'
    ), name='password_change'),

     path('change-password/done/', password_change_done, name='password_change_done'),

     path('proceed-to-checkout/', proceed_to_checkout, name='proceed_to_checkout'),
     path('return-to-me/', payment_return, name='payment_return'),
     path('pay/', pay, name='pay'),
     path('logoutpage/', logout_view, name='logout')
    #  path('add_to_cart_in')

]

ecommerce_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    profile_picture = models.ImageField(upload_to='profile_picture/',default="profile_picture/default.jpg", blank=False)

    def __str__(self):
        return self.username


class Product(models.Model):
    product_name = models.CharField(max_length=100)
    product_details = models.TextField()
    product_price = models.DecimalField(max_digits=10, decimal_places=2)
    product_image = models.ImageField(upload_to='products/', blank=False)

    def __str__(self):
        return self.product_name


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.product.product_name


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    order_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.product_name
    

ecommerce_app/forms.py
from django import forms
from .models import User, Product
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UsernameField


class UserForm (UserCreationForm):
    class Meta:
        model = User
        fields = ('username','email','password1','password2','profile_picture')


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('product_name', 'product_details', 'product_price', 'product_image')

ecommerce_app/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from .forms import UserForm, ProductForm
from .models import User, Cart, Product, Order
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
import jsons
import base64
import requests
import shortuuid
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.backends import default_backend
from datetime import datetime
from django.views.decorators.cache import cache_control
from django.db.models import Count

# Create your views here.


########### Home, UserRegistration and Login ################
def home(request):
    products = Product.objects.all()
    # cart = Cart.objects.all()
    cart_product_id = []
    top_two = []
    quantity = 0
    if request.user.is_authenticated:
        user_id = request.user.id
        quantity = Cart.objects.filter(user_id=user_id).count()

        cart_filter = Cart.objects.filter(user_id=user_id)
        for id in cart_filter:
            cart_product_id.append(id.product_id)

    product_counts = Order.objects.values('product').annotate(product_count=Count('product')).order_by('-product_count')[:2]
    for i in product_counts:
        product = Product.objects.get(pk=i['product'])
        top_two.append(product)


    # print(cart_id)
    context = {
        'products': products,
        'quantity': quantity,
        'cart_product_id': cart_product_id,
        'top_two' : top_two
    }
    return render(request, 'home.html', context)


def register_user(request):
    form = UserForm()
    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()

        form = UserForm()
        return render(request, 'register.html', {'form': form})
    return render(request, 'register.html', {'form': form})


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        products = Product.objects.all()
        context = {
            'products': products
        }
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return render(request, 'home.html', context)
        else:
            return messages.error(request, 'Invalid username or password')
    return render(request, 'login.html')



def product_register(request):
    form = ProductForm()
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        form = ProductForm()
        return render(request, 'product_register.html', {'form':form})
    return render(request, 'product_register.html', {'form': form})


################### Cart ################
@login_required
def add_to_cart(request,product_pk):
    if request.user.is_authenticated:
        price = Product.objects.get(pk=product_pk).product_price
        user_id = request.user.id
        product_id = product_pk
        Cart.objects.create(user_id=user_id, product_id=product_id, price=price, total_price=1*price)

        quantity = Cart.objects.filter(user_id=user_id).count()
        context = {
            'quantity': quantity
        }
        return redirect(reverse('ecommerce:home') + f'?quantity={quantity}')
    return render(request, 'home.html')

@login_required
def go_to_cart(request):
    user_id = request.user.id
    cart = Cart.objects.filter(user_id=user_id)

    quantity = Cart.objects.filter(user_id=user_id).count()
    
    total_price = 0
    for item in cart:
        total_price += item.total_price
    
    context = {
        'cart_items': cart,
        'total_price': total_price,
        'quantity': quantity
    }
    return render(request, 'cart.html', context)

@login_required
def increase_cart_items(request, cart_pk):
    cart = Cart.objects.get(pk=cart_pk)
    cart.quantity += 1
    cart.total_price = cart.price * cart.quantity
    cart.save()
    return redirect('ecommerce:go_to_cart')

@login_required
def decrease_cart_items(request, cart_pk):
    cart = Cart.objects.get(pk=cart_pk)
    cart.quantity -= 1
    if cart.quantity == 0:
        cart = Cart.objects.get(pk=cart_pk)
        cart.delete()
        return redirect('ecommerce:go_to_cart')
    
    cart.total_price -= cart.price
    cart.save()
    return redirect('ecommerce:go_to_cart')


@login_required
def remove_from_cart(request, cart_pk):
    cart = Cart.objects.get(pk=cart_pk)
    cart.delete()
    return redirect('ecommerce:go_to_cart')

##################### Product Details Page ##################

def product_detail_tab(request, product_id):
    # product = get_object_or_404(Product, id=product_id)
    product = Product.objects.get(id = product_id)
    cart_list = []
    user_id = request.user.id
    quantity = Cart.objects.filter(user_id=user_id).count()
    if request.user.is_authenticated:
        user_id = request.user.id
        cart_product_id = Cart.objects.filter(user_id = user_id)
        for i in cart_product_id:
            cart_list.append(i.product_id)
    
    context = {
        'product': product,
        'cart':cart_list,
        'quantity':quantity
     }
    return render(request, 'product_details.html', context)



############################## Profile Page ######################################
@login_required
def profile_page(request, profile_id):
    if request.user.is_authenticated:
        user = User.objects.get(pk = profile_id)
        quantity = Cart.objects.filter(user_id = profile_id).count()
        context ={
            'user':user,
            'quantity':quantity
        }
        return render(request, 'profile.html', context)
    else:
        return redirect('ecommerce:home')

@login_required  
def update_username(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            user = User.objects.get(id=request.user.id)
            user_id = user.id
            username = request.POST['username']
            user.username = username
            user.save()
            return redirect('ecommerce:profile_page', profile_id=user_id)
    return render(request, 'update_username.html')

@login_required
def update_profile_pic(request):
    if request.method == 'POST':
        user = User.objects.get(id=request.user.id)
        user_id = user.id

        if request.FILES:
            existing_pro_pic = user.profile_picture
            existing_pro_pic.delete(save=True)
            profile_picture = request.FILES['profile_picture']
            user.profile_picture = profile_picture
            user.save()
            return redirect('ecommerce:profile_page', profile_id=user_id)
        else:
            return HttpResponse('Please select a file')
        
    return render(request, 'update_profile_pic.html')
@login_required
def change_password(request):
    pass

@login_required
def password_change_done(request):
    return redirect('ecommerce:home')

@login_required
def proceed_to_checkout(request):
    cart = Cart.objects.filter(user_id=request.user.id)
    total_price = 0
    for item in cart:
        total_price += item.total_price
    context = {
        'cart_items': cart,
        'total_price': total_price
    }
    return render(request, 'payment.html',context)


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def logout_view(request):
    logout(request)
    response = redirect('ecommerce:home')
    response.delete_cookie('csrftoken')
    return response

################################## Phone Pay integration ########################################

############### Helper Function ################
def calculate_sha256_string(input_string):
    # Create a hash object using the SHA-256 algorithm
    sha256 = hashes.Hash(hashes.SHA256(), backend=default_backend())
    # Update hash with the encoded string
    sha256.update(input_string.encode('utf-8'))
    # Return the hexadecimal representation of the hash
    return sha256.finalize().hex()
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
def base64_encode(input_dict):
    # Convert the dictionary to a JSON string
    json_data = jsons.dumps(input_dict)
    # Encode the JSON string to bytes
    data_bytes = json_data.encode('utf-8')
    # Perform Base64 encoding and return the result as a string
    return base64.b64encode(data_bytes).decode('utf-8')
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
########################## Create your views here. ########################
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# def index(request):
#     return render(request, "index.html", { 'output': "Please Pay & Repond From The Payment Gateway Will Come In This Section", 'main_request': "" })

@login_required
def pay(request):
    cart = Cart.objects.filter(user_id=request.user.id)
    total_price = 0
    for item in cart:
        total_price += int(item.total_price)
    MAINPAYLOAD = {
        "merchantId": "PGTESTPAYUAT",
        "merchantTransactionId": shortuuid.uuid(),
        "merchantUserId": "MUID123",
        "amount": total_price*100,
        "redirectUrl": "http://127.0.0.1:8000/return-to-me/",
        "redirectMode": "POST",
        "callbackUrl": "http://127.0.0.1:8000/return-to-me/",
        "mobileNumber": "9999999999",
        "paymentInstrument": {
            "type": "PAY_PAGE"
        }
    }
    # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    # SETTING
    # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    INDEX = "1"
    ENDPOINT = "/pg/v1/pay"
    SALTKEY = "099eb0cd-02cf-4e2a-8aca-3e6c6aff0399"

ecommerce_app/templates/cart.html
{% extends 'base.html' %}

{% block content %}
<h2>Your Shopping Cart</h2>
<hr>
<table>
    <thead>
        <tr>
            <th>Product</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for items in cart_items %}
        <!-- Sample Product 1 -->
        <tr>
            <td>
                <img src="{{ items.product.product_image.url }}" alt="Product 1" style="width: 50px; height: 50px; margin-right: 10px;">
                {{ items.product.product_name }}
            </td>
              <td>{{ items.product.product_price }}</td>
            <td>
                <a href="{% url 'ecommerce:decrease_cart_items' items.pk %}"><button>-</button></a>
                <span>{{ items.quantity }}</span>
                <a href="{% url 'ecommerce:increase_cart_items' items.pk %}"><button>+</button></a>
            </td>
            <td>${{ items.total_price }}</td>
            <td><a href="{% url 'ecommerce:remove_from_cart' items.pk %}" class="checkout" style="background-color: #FF6347;">Remove from cart</a></td>
            
        </tr>

        {% endfor %}

    </tbody>
</table>
<div class="total">Total: {{ total_price }}</div>
<a href="{% url 'ecommerce:proceed_to_checkout' %}" class="checkout">Proceed to Checkout</a>
{% endblock %}

ecommerce_app/templates/change_password.html
{% extends 'base.html' %}
{% block content %}

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}


    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>
{% endblock %}

ecommerce_app/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Slide of images -->
<div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'images/bvlgari.jpg' %}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/homme.jpg' %}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/showcase.jpg' %}" class="d-block w-100" alt="...">
      </div>
    </div>
    <!-- <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button> -->
  </div>



{% if top_two %}
<h3>Our Best Selling Products</h3>

<div class="home_content">
  <div class="product-grid">
      <!-- Product 1 -->
      {% for product in top_two %}
      
      <div class="product-card">
          <img class="product-image" src="{{ product.product_image.url }}" alt="Products">
          <div class="product-info">
              <a href="{% url 'ecommerce:product_detail_tab' product.pk %}"><div class="product-name">{{ product.product_name }}</div></a>
              <div class="product-description">{{ product.product_details }}</div>
              <div class="product-price">${{ product.product_price }}</div>
          </div>
        
          <div class="button-card">
            {% csrf_token %}
                {% if request.user.is_authenticated %}
                  {% if product.pk in cart_product_id %}
                  <a href="{% url 'ecommerce:go_to_cart' %}"><button style="background-color: #ff6f61">Go to cart</button></a>
                  {% else %}
                  <a href="{% url 'ecommerce:add_to_cart' product.pk %}"><button>Add to cart</button></a>
                  {% endif %}
                {% endif %}

                {% if not request.user.is_authenticated %}
                <a href="{% url 'ecommerce:add_to_cart' product.pk %}"><button>Add to cart</button></a>
                {% endif %}

                <!-- <p>{{ product.pk }}</p> -->
          </div>
      </div>
      {% endfor %}
  </div>

</div>
{% endif %}



<h3>Our Products</h3>
<!-- The product prices -->
<div class="home_content">
    <div class="product-grid">
        <!-- Product 1 -->
        {% for product in products %}
        
        <div class="product-card">
            <img class="product-image" src="{{ product.product_image.url }}" alt="Products">
            <div class="product-info">
                <a href="{% url 'ecommerce:product_detail_tab' product.pk %}"><div class="product-name">{{ product.product_name }}</div></a>
                <div class="product-description">{{ product.product_details }}</div>
                <div class="product-price">${{ product.product_price }}</div>
            </div>
          
            <div class="button-card">
              {% csrf_token %}
                  {% if request.user.is_authenticated %}
                    {% if product.pk in cart_product_id %}
                    <a href="{% url 'ecommerce:go_to_cart' %}"><button style="background-color: #ff6f61">Go to cart</button></a>
                    {% else %}
                    <a href="{% url 'ecommerce:add_to_cart' product.pk %}"><button>Add to cart</button></a>
                    {% endif %}
                  {% endif %}

                  {% if not request.user.is_authenticated %}
                  <a href="{% url 'ecommerce:add_to_cart' product.pk %}"><button>Add to cart</button></a>
                  {% endif %}

                  <!-- <p>{{ product.pk }}</p> -->
            </div>
        </div>
        {% endfor %}
    </div>

</div>
{% endblock %}

ecommerce_app/templates/login.html
{% extends 'base.html' %}
{% block content %}

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}


    <form action="" method="POST">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" placeholder="username" name="username">
        <label for="password">Password:</label>
        <input type="password" placeholder="password" name="password">
        <button type="submit">Login</button>
    </form>
{% endblock %}

ecommerce_app/templates/payment.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'ecommerce:pay' %}" method="get">
    <section style="background-color: #eee;">
    <h3 class="text-center">PHONEPAY PAYMENT DEMO BY CODE 180 </h3>
      <div class="container py-5">
        <div class="row d-flex justify-content-center">
          <div class="col-md-8 col-lg-6 col-xl-4">
            <div class="card rounded-3">
              <div class="card-body mx-1 my-2">
                <div class="d-flex align-items-center">
                  <div>
                    <i class="fab fa-cc-visa fa-4x text-black pe-3"></i>
                  </div>
                  <div>
                    <p class="d-flex flex-column mb-0">
                      <b>Code 180 Demo Card</b><span class="small text-muted">**** 7420</span>
                    </p>
                  </div>
                </div>
                <div class="pt-3">
                  <div class="d-flex flex-row pb-3">
                    <div class="rounded border border-primary border-2 d-flex w-100 p-3 align-items-center"
                      style="background-color: rgba(18, 101, 241, 0.07);">
                      <div class="d-flex align-items-center pe-3">
                        <!-- <input class="form-check-input" type="radio" name="radioNoLabelX" id="radioNoLabel11"
                          value="" aria-label="..." checked /> -->
                      </div>
                      <div class="d-flex flex-column">
                        <p class="mb-1 small text-primary">Checkout</p>
                        <h6 class="mb-0 text-primary">{{ total_price }}</h6>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="d-flex justify-content-between align-items-center pb-1">
                  <a href="#!" class="text-muted">Go back</a>
                  <button type="submit" class="btn btn-danger btn-lg">Pay amount</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    </form>
    <section style="background-color: #d5d4d4;">
    <div class="container py-5">
        <div class="row d-flex justify-content-center">
          <h3 class="text-center">CHECKOUT RESPONSE</h3>
          <br><br>
          {{ output }}
          <br><br>
          {{ main_request }}
        </div>
    </div>
    </section>
{% endblock %}

ecommerce_app/templates/payment_failed.html
{% extends 'base.html' %}
{% block content %}
<p>PAYMENT FAILED</p>
<a href="{% url 'ecommerce:home' %}">Return to home page</a>
{% endblock %}

ecommerce_app/templates/payment_success.html
{% extends 'base.html' %}
{% block content %}
<div class="card-main-body">
    <div class="card">
      <div class="green-tick">&#10004;</div>
      <div>
          <p>Your payment is successful.</p>
          <p>{{ transact_id }}</p>
          <p> You paid : {{ amount }}</p>
      </div>
    </div>
    <div>
        <a href="{% url 'ecommerce:home' %}">Go to home page</a>
    </div>
</div>

{% endblock %}

ecommerce_app/templates/product_details.html
{% include 'base.html' %}


  <div class="product-details-container">
    
    <div class="product-details-image" style="--product-image: url({{ product.product_image.url }});">
      
    </div>

    <div class="product-details-details">
      <h1>{{ product.product_name }}</h1>
      <p class="details-price">${{ product.product_price }}</p>
      <p class="details-description">{{ product.product_details }}</p>

      {% if request.user.is_authenticated %}
      {% if product.pk in cart %}
      <a href="{% url 'ecommerce:go_to_cart' %}"><button class="add-to-cart-btn" style="background-color: #ff6f61;">Go to Cart</button></a>
      {% else %}
      <a href="{% url 'ecommerce:add_to_cart' product.pk %}"><button class="add-to-cart-btn">Add to Cart</button></a>
      {% endif %}
      {% endif %}

      {% if not request.user.is_authenticated %}
      <a href="{% url 'ecommerce:login_user' %}"><button class="add-to-cart-btn">Login to Add to Cart</button></a>
      {% endif %}
    </div>
  </div>

ecommerce_app/templates/product_register.html
{% extends 'base.html' %}
{% block content %}

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Add Product</button>
</form>

{% endblock %}

ecommerce_app/templates/profile.html
{% extends 'base.html' %}


{% block content %}
<div class="profile-container">
  <div class="profile-details">
    <img src="{{ user.profile_picture.url }}" alt="Profile Picture" class="rounded-profile" name="profile_picture">
    <h2>{{ user.username }}</h2>
  </div>
  <div class="profile-actions">
    <a href="{% url 'ecommerce:update_username' %}"><button>Update Username</button></a>
    <a href="{% url 'ecommerce:password_change' %}"><button>Change Password</button></a>
    <a href="{% url 'ecommerce:update_profile_pic' %}"><button>Change Profile Picture</button></a>
    <a href="{% url 'ecommerce:logout' %}"><button>Log out</button></a>
  </div>
</div>

{% endblock %}

ecommerce_app/templates/register.html
{% extends 'base.html' %}
{% block content %}

<form action="" method="POST" enctype="multipart/form-data">
{% csrf_token %}
{{ form.as_p }}
<button type="submit">Register</button>
</form>

{% endblock %}

ecommerce_app/templates/update_profile_pic.html
{% extends 'base.html' %}



{% block content %}
    <h2>Update Profile Picture</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="profile_pic">Upload Profile Picture</label>
        <input type="file" name="profile_picture" id="profile_pic">

        <button type="submit">Update</button>
    </form>

{% endblock %}

ecommerce_app/templates/update_username.html
{% extends 'base.html' %}

{% block content %}
    <h2>Update Username</h2>
    <form method="POST">
        {% csrf_token %}
        <label for="username">New Username</label>
        <input type="text" name="username" id="username">

        <button type="submit">Update</button>
    </form>

{% endblock %}